package com.javatech.aws.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor 
@NoArgsConstructor

@DynamoDBTable(tableName = "person")

public class Person  implements Serializable{
	@DynamoDBHashKey  (attributeName = "personId")
	@DynamoDBAutoGeneratedKey
	private String personId;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String cpf;
	@DynamoDBAttribute
	private String telefone;
	@DynamoDBAttribute
	private String agencia ;
	@DynamoDBAttribute
	private String conta ;
	@DynamoDBAttribute
	private String dataNascimento;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private Address address;
	public String getPersonId() {
		// TODO Auto-generated method stub
		return personId;
	}
	
	
}
